name: Test Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd backend
          bun install

      - name: Run tests
        run: |
          cd backend
          bun test ./tests/*.ts

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and start services
        run: docker compose -f local.docker-compose.yml up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to start..."
          sleep 15
          
          echo "Checking if HAProxy is responding..."
          curl --retry 20 --retry-delay 3 --retry-connrefused --fail http://localhost:3000
          
          echo "Testing API health endpoint..."
          curl --retry 15 --retry-delay 3 --retry-connrefused --fail http://localhost:3000/api/health
          
          echo "Services are ready!"

      - uses: grafana/setup-k6-action@v1
      - uses: grafana/run-k6-action@v1
        env:
          BASE_URL: http://localhost:3000/api
        with:
          path: |
            ./backend/tests/performance/*.js

      - name: Clean up
        if: always()
        run: |
          if [ "${{ job.status }}" = "failure" ]; then
            echo "=== Service logs ==="
            docker compose -f local.docker-compose.yml logs
          fi
          docker compose -f local.docker-compose.yml down
